// <auto-generated />
using System;
using MariCamiStore.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MariCamiStore.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(MariCamiStoreContext))]
    [Migration("20240914195739_InitialMigration-2")]
    partial class InitialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MariCamiStore.Model.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeRateMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LocalCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ServiceFeeInLocalCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Configurations", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64b4d953-66d6-409e-929d-6036111fb712"),
                            ExchangeRate = 520m,
                            ExchangeRateMargin = 30m,
                            LocalCurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb710"),
                            OrganizationId = new Guid("64b4d953-66d5-409e-929d-6036111fb710"),
                            ServiceFeeInLocalCurrency = 3000m,
                            TaxPercentage = 7m
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb710"),
                            Abbreviation = "COL",
                            Name = "Colones"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Abbreviation = "USD",
                            Name = "Dolares"
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64b4d953-66d5-409e-929d-6036111fb710"),
                            Name = "MariCamiStore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
