// <auto-generated />
using System;
using MariCamiStore.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MariCamiStore.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(MariCamiStoreContext))]
    [Migration("20260611203602_AddCustomerIsGeneric")]
    partial class AddCustomerIsGeneric
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MariCamiStore.Model.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeRateMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("LocalCurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderCurrencyIdDefault")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductTypeIdDefault")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Configurations", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64b4d953-66d6-409e-929d-6036111fb712"),
                            ExchangeRate = 510m,
                            ExchangeRateMargin = 20m,
                            LocalCurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb710"),
                            OrderCurrencyIdDefault = new Guid("64b4d953-66d5-409e-929d-6036111fb711"),
                            OrganizationId = new Guid("64b4d953-66d5-409e-929d-6036111fb710"),
                            ProductTypeIdDefault = new Guid("73b4d953-66d5-409e-929d-6036111fb712"),
                            TaxPercentage = 7m
                        },
                        new
                        {
                            Id = new Guid("64b4d953-66d6-409e-929d-6036111fb713"),
                            ExchangeRate = 530m,
                            ExchangeRateMargin = 20m,
                            LocalCurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb710"),
                            OrderCurrencyIdDefault = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            OrganizationId = new Guid("64b4d953-66d5-409e-929d-6036111fb712"),
                            TaxPercentage = 13m
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sign")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb710"),
                            Abbreviation = "COL",
                            Name = "Colones",
                            Sign = "₡"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Abbreviation = "USD",
                            Name = "Dolares",
                            Sign = "$"
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGeneric")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LocationLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            Address = "San José, Costa Rica",
                            Email = "prueba@test.com",
                            IsGeneric = false,
                            Name = "Cliente de Prueba",
                            NickName = "Cliente Prueba",
                            PhoneNumber = "8888-0000"
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.CxPEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PeriodControlId");

                    b.ToTable("CxPEntries", "dbo");
                });

            modelBuilder.Entity("MariCamiStore.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ActualShippingAmountToCR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedProfitInLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NameOfOrder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ShippingAmountIntern")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShippingAmountToCR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAgreedPriceInLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalOfTheOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalToPayToSupplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalWithoutTaxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders", "dbo");
                });

            modelBuilder.Entity("MariCamiStore.Model.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AgreedPriceInLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EstimateShipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ListPriceTaxWithTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("ProductImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductSourceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("RealPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceFeeInLocal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", "dbo");
                });

            modelBuilder.Entity("MariCamiStore.Model.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Justification")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TransitionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistory", "dbo");
                });

            modelBuilder.Entity("MariCamiStore.Model.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organizations", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64b4d953-66d5-409e-929d-6036111fb710"),
                            Name = "MariCamiStore"
                        },
                        new
                        {
                            Id = new Guid("64b4d953-66d5-409e-929d-6036111fb712"),
                            Name = "Testing"
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.PeriodControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PagosRealizados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TransactionMonth")
                        .HasColumnType("int");

                    b.Property<int>("TransactionYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "TransactionMonth", "TransactionYear")
                        .IsUnique();

                    b.ToTable("PeriodControls", "dbo");
                });

            modelBuilder.Entity("MariCamiStore.Model.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EstimateShipping")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ServiceFeeInLocal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb710"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Joyeria, bisuteria, adornos corporales.",
                            EstimateShipping = 1m,
                            Name = "Pequeños",
                            ServiceFeeInLocal = 800m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb711"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Uñas, prendas pequeñas",
                            EstimateShipping = 2m,
                            Name = "Pequeños medio",
                            ServiceFeeInLocal = 1000m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb712"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Camisas, vestidos, ropa interior, leggis, etc.",
                            EstimateShipping = 3m,
                            Name = "Prendas de ropa normales",
                            ServiceFeeInLocal = 1500m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb713"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Juegos de camisas, o conjuntos.",
                            EstimateShipping = 4m,
                            Name = "Paquetes de Prendas",
                            ServiceFeeInLocal = 1500m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb714"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Jeans, Jackets",
                            EstimateShipping = 4m,
                            Name = "Prendas pesadas",
                            ServiceFeeInLocal = 2500m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb715"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Zapatos o tennis livianas",
                            EstimateShipping = 4m,
                            Name = "Zapatos livianos",
                            ServiceFeeInLocal = 2000m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb716"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Zapatos o tennis",
                            EstimateShipping = 5m,
                            Name = "Zapatos",
                            ServiceFeeInLocal = 2500m
                        },
                        new
                        {
                            Id = new Guid("73b4d953-66d5-409e-929d-6036111fb717"),
                            CurrencyId = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Description = "Para armar promos propias",
                            EstimateShipping = 3m,
                            Name = "Promos",
                            ServiceFeeInLocal = 2500m
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb710"),
                            Name = "Shein"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb711"),
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb712"),
                            Name = "Puma"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb713"),
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb714"),
                            Name = "Ross y otros"
                        },
                        new
                        {
                            Id = new Guid("63b4d953-66d5-409e-929d-6036111fb715"),
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("MariCamiStore.Model.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions", "dbo");
                });

            modelBuilder.Entity("MariCamiStore.Model.CxPEntry", b =>
                {
                    b.HasOne("MariCamiStore.Model.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MariCamiStore.Model.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MariCamiStore.Model.PeriodControl", "Period")
                        .WithMany("Entries")
                        .HasForeignKey("PeriodControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("MariCamiStore.Model.OrderItem", b =>
                {
                    b.HasOne("MariCamiStore.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MariCamiStore.Model.OrderStatusHistory", b =>
                {
                    b.HasOne("MariCamiStore.Model.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MariCamiStore.Model.PeriodControl", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
