name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build
        run: dotnet build MariCamiStore/MariCamiStore.csproj --configuration Release

      - name: Publish
        run: dotnet publish MariCamiStore/MariCamiStore.csproj --configuration Release --output ${{ env.DOTNET_ROOT }}/myapp

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ABBFE57878534551A7BCB2708B86D8B6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72CE75462F534C13BF6071F3411225E3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28D600E5948E423598E0C2A278A4C915 }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'maricamistoreweb'
          slot-name: 'Production'
          package: .
